pub mod acp;
#[cfg(feature = "acp-mcp")]
pub mod acp_mcp;
pub mod adapter;
pub mod bot_turns;
pub mod config;
pub mod cron;
pub mod directives;
pub mod dispatch;
pub mod error_display;
#[cfg(feature = "filestore")]
pub mod filestore;
pub mod format;
pub mod gateway;
pub mod hooks;
pub mod markdown;
pub mod media;
pub mod multibot_cache;
#[cfg(feature = "pre-seed")]
pub mod pre_seed;
pub mod reactions;
pub mod redact;
#[cfg(feature = "discord")]
pub mod remind;
pub mod secrets;
pub mod setup;
pub mod stt;
pub mod timestamp;
pub mod trust;

#[cfg(feature = "discord")]
pub mod ambient;
#[cfg(feature = "discord")]
pub mod discord;
#[cfg(feature = "matrix")]
pub mod matrix;
#[cfg(feature = "mattermost")]
pub mod mattermost;
#[cfg(feature = "slack")]
pub mod slack;
